### ISSUE TITLE
Missing cl2

### ISSUE THREAD

**Issue by wheybags** [mewrnd/blizzconv#4]
You seem to be missing monsters\darkmage\dmagew.cl2 ?
I'm not sure how to add it, I tried just copying the section for dmagea but that didn't work.

**Comment by wheybags** [comment]
also monsters/mage/magew.cl2 and monsters/mega/megah.cl2

**Comment by mewmew** [comment]
It should be possible to translate `mageh.cl2` and `magew.cl2` to PNG images using the following commands.

```
img_dump -imgini=cl2.ini mageh.cl2 mageh{0..7}.cl2
img_dump -imgini=cl2.ini magew.cl2 magew{0..7}.cl2
```

The `mageh.cl2` images are located in `_dump_/monsters/mage/mageh[0-7]/`, while the `magew.cl2` images are located in `_dump_/monsters/mage/magew[0-7].png` and `_dump_/monsters/mage/{cnselbk,cnselg,cnselgd,general,infra}.trn/magew[0-7].png`.

Note that the mage uses teleport to move, and does not use a walk animation. Therefore `magew.cl2` contains a single frame, which is fully transparent.

More perplexing is perhaps the `dmagew.cl2` animation, the file size of which is 96 bytes in total. We've not yet been able to decode the `dmagew.cl2` animation. However, the file size alone would suggest that it does not contain any pixel data, and may therefore be considered analogous to the walk animation of mage, e.g. none existent.

As `dmagew.cl2` contains no pixel data it has not been added to the `cl2.ini` file, perhaps incorrectly so?

Let me know if you manage to decode `magew.cl2`, which should produce a single transparent frame, and `mageh.cl2`, which should produce the graphic hit animation of the mage.

**Comment by mewmew** [comment]
Note, simply invoking `img_dump -imgini=cl2.ini mageh.cl2` will not extract the frames of the `mageh` animation, but rather extract the `mageh` CL2 archive, to create the files `mageh[0-7].cl2`. The subsequent invocation of the command `img_dump -imgini=cl2.ini mageh[0-7].cl2` extracts the actual animation graphics from the 8 CL2 images (e.g. `mageh[0-7].cl2`), one for each direction.

**Comment by wheybags** [comment]
Aaah, ok, I found dmagew wasnt in the ini file so then I presumed the others weren't either.
(I've been writing some tests to compare freeablo's image decoding output with yours, found those files weren't where I expected them to be in the _dump_ folder so I thought they were just missing)

**Comment by mewmew** [comment]
> found those files weren't where I expected them to be in the dump folder so I thought they were just missing.

Right. I understand the confusion as I was also confused by the output location of these images today while tracking down this issue. The reason that the `magew` animation images where located in the `monsters/mage/` directory, rather than `monsters/mage/magew[0-7]` is simply because the `blizzconv` tool tried to be cleaver. It does not create directories for animations only containing a single frame. This seemed like the right decision for animations containing a single frame and using a single palette, such as those present in `gendata/`.

The  `blizzconv` tools were developed a long time ago, and they are starting to show their age. A rewrite may happen at some point, but for now, we will try to maintain the blizzconv repo and make sure it covers all the major use cases.
